yqnet/db_yqn/urls.py
# Copyright: Michael Wood 2019
# Web: http://michaelwood.me.uk
# License: LICENSE.txt

from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from db_yqn import api, custom_api

app_name = "yqn_api"

urlpatterns = [
    path('Posts/', api.PostList.as_view()),
    path('Post/<int:pk>/', api.PostDetail.as_view()),
    path('Post/<int:pk>/comments/', api.CommentsPost.as_view()),
    path('XMLFeeds/', api.XMLFeedList.as_view()),
    path('XMLFeed/<int:pk>/', api.XMLFeedDetail.as_view()),
    path('Twitters/', api.TwitterList.as_view()),
    path('Twitter/<int:pk>/', api.TwitterDetail.as_view()),
    path('Instagrams/', api.InstagramList.as_view()),
    path('Instagram/<int:pk>/', api.InstagramDetail.as_view()),

    path('GroupPages/', api.GroupPagesList.as_view()),
    path('GroupPage/<int:pk>', api.GroupPageDetail.as_view()),
    path('GroupPage/<int:pk>/images', api.GroupPageDetailImages.as_view()),
    path('GroupRedirectPages/', api.GroupPagesRedirectList.as_view()),

    path('EventsLocations/', api.EventsLocationList.as_view()),
    path('EventsLocation/<int:pk>/', api.EventsLocationDetail.as_view()),

    path('Venues/', api.VenueList.as_view(), name="venues"),

    path('Events/', api.EventList.as_view()),
    path('Event/<int:pk>/', api.EventDetail.as_view()),

    path('Regions/', api.RegionList.as_view()),

    path('EventsAtVenue/', api.EventsAtVenue.as_view()),
    path('EventsAtRegion/', api.EventsAtRegion.as_view()),

    path('Contact/', custom_api.Contact.as_view()),
    path('Upload/', custom_api.Upload.as_view(), name="media-upload"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

yqnet/ui_yqn/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django_registration.backends.one_step.views import RegistrationView
from django.views.generic.base import TemplateView

from ui_yqn import views

urlpatterns = [
    path('', views.PostsView.as_view(), name="index"),

    path('about/', TemplateView.as_view(template_name="about.html"), name="about"),
    path('privacy/', TemplateView.as_view(template_name="privacy.html"), name="privacy"),
    path('contact/', TemplateView.as_view(template_name="contact_yqn.html"), name="contact"),
    path('whatsapp/', TemplateView.as_view(template_name="whatsapp.html"), name="whatsapp"),
    path('search/', TemplateView.as_view(template_name="search.html"), name="search"),

    path('posts/', views.PostsView.as_view(), name="posts"),
    path('post/<int:pk>/', views.PostsView.as_view(), name="post"),
    path('posts/twitter/', views.TwittersView.as_view(), name="twitters"),
    path('posts/instagram/', views.InstagramView.as_view(), name="instagram"),

    path('events/list/', views.EventsListingView.as_view(), name="events"),
    path('events/map/', views.MapView.as_view(), name="map"),
    path('event/<int:pk>/', views.EventView.as_view(), name="event"),

    path('venue/<int:pk>/', views.EventsAtVenueView.as_view(), name="venue"),

    path('groups/', views.GroupPagesView.as_view(), name="pages"),

    path('api/', include('db_yqn.urls', namespace="api")),

    # Acounts stuff
    path('accounts/edit', views.UpdateUserDetailsView.as_view(), name="edit-profile"),
    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/register/',
        RegistrationView.as_view(success_url=reverse_lazy("index")),
        name='django_registration_register'),

    path('accounts/', include('django_registration.backends.one_step.urls')),


    path('oauth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),


    # Capture all other url paths before this one
    path('<slug:slug>/', views.GroupPageView.as_view(), name="user-pages"),
    path('<slug:slug>/edit/', views.GroupPageEditView.as_view(),
         name="user-page-edit"),
    path('<slug:slug>/events/', views.EventsListingView.as_view(),
         name="user-page-events"),

    # temp
    path("<slug:slug>/permissions/<int:pk>", views.GroupPageEditorsUpdate.as_view(), name="user-page-permissions"),
]


# Dev purposes
# Media upload files serving for dev purposes
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Make sure we don't see 404 errors for the favicon
# In production this would be provided by the webserver
urlpatterns += [
    path('favicon.ico',RedirectView.as_view(url='%simgs/fav/favicon-16x16.png' % settings.STATIC_URL)),
]

yqnet/ui_yqn/views.py
# Copyright: Michael Wood 2019
# Web: http://michaelwood.me.uk
# License: LICENSE.txt
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy

import datetime
from db_yqn.models import Post, Twitter, GroupPage, Event, EventsLocation, Venue
from db_yqn.models import UserMedia
from settings_yqn import settings


# Not in use
class IndexView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        posts = Post.objects.order_by('-id').exclude(private=True)[:3]
        events = Event.objects.order_by('-id').exclude(private=True)[:3]
        events_location = EventsLocation.objects.exclude(private=True).order_by('-id')[:3]
        pages = GroupPage.objects.order_by("-last_updated")[:3]

        context['posts'] = posts
        context['events'] = events
        context['events_location'] = events_location
        context['pages'] = pages

        return context
# End not in use

# Posts
class PostsView(TemplateView):
    template_name = "posts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['total_posts'] = Post.objects.count()
        return context

class TwittersView(PostsView):
    template_name = "twitters.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        twitter = Twitter.objects.order_by('?')
        context['twitter'] = twitter

        return context

class InstagramView(PostsView):
    template_name = "instagram.html"

# End Posts

# TODO We'll probably do this more dynamically than in these templates

class EventsView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        total = Event.objects.count()
        total = total + EventsLocation.objects.count()

        context['total_events'] = total
        return context

# Note these inherit from the EventsView which is why they're not
# direct templates
class EventView(EventsView):
    template_name = "event.html"

class MapView(EventsView):
    template_name = "map.html"

class EventsListingView(EventsView):
    template_name = "events_listings.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if kwargs.get("slug"):
            context['group_page'] = GroupPage.objects.get(slug=kwargs['slug'])

        return context

class EventsAtVenueView(EventsView):
    template_name = "events_at_venue.html"

class GroupPageView(TemplateView):
    template_name = "user_page.html"
    page = None

    def get(self, request, *args, **kwargs):
        self.page = get_object_or_404(GroupPage, slug=kwargs['slug'])
        if self.page.redirect:
            return redirect(self.page.redirect)

        return super().get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['user_can_edit'] = False
        context['user_can_edit'] = self.page.can_user_edit(self.request.user)

        context['page'] = self.page

        return context

class GroupPageEditView(GroupPageView, LoginRequiredMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['editing'] = True

        return context


class GroupPagesView(TemplateView):
    template_name = "user_pages.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['pages'] = GroupPage.objects.all().order_by("-last_modified")
        context['origin'] = self.request.META['HTTP_HOST']

        return context

class UpdateUserDetailsView(UpdateView, LoginRequiredMixin):
    template_name = "update_userdetails.html"
    model = User
    fields = ['username','first_name', 'last_name', 'email']
    success_url = "?result=success"

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context['current_avatar'] = UserMedia.objects.get(user=self.request.user, file_upload__contains="yqn-avatar-").file_upload.url
        except UserMedia.DoesNotExist as e:
            print(e)
            context['current_avatar'] = settings.STATIC_URL + '/imgs/fav/android-chrome-192x192.png'

        return context

# TEMP TODO this. This is a clunky way to edit the permissions.
# Will be relaced once a proper ui is designed.
class GroupPageEditorsUpdate(UpdateView, LoginRequiredMixin):
    template_name = "update_grouppage_editors.html"
    fields = ['users']
    success_url = "?result=success"
    model = GroupPage

    def get_object(self, **kwargs):
        page = super().get_object(**kwargs)

        if not page.can_user_edit(self.request.user):
            raise PermissionDenied("User not allowed")

        return page

yqnet/ui_yqn/templates/android_post_auth.html
{% load static %}
<!doctype html>
<html lang="en">
    <!-- Copyright Michael Wood 2019 -->
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="theme-color" content="#343a40">

        <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    </head>
    <body class="bg-dark">
        <div class="mt-3 d-flex flex-column justify-content-center p-2">
            <a href="{{app_link}}" class="ml-auto mr-auto text-center">
                <img src="{% static "imgs/logo_yqn.png" %}" class="mb-3">
                <h2 class="text-reset">Login Success</h2>
            </a>
            <a href="{{app_link}}" class="btn btn-primary mt-3">Continue</a>
        </div>
    </body>
</html>

yqnet/ui_yqn/templates/contact_yqn.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
{% load static %}
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="clearfix border-bottom border-gray pb-2 mb-2  ">

        <h6 class="float-left">Contact</h6>
    </div>

    <div class="m-2">

        <h2>Contact</h2>
        <p>If you have any questions or issues please don't hesitate to contact us on info@<span id="domain"></span></p>
    </div>

</div>

<script>
    $(document).ready(function(){
        $("#domain").text("quakr.net");
    });
</script>


{% endblock %}

yqnet/ui_yqn/templates/posts.html
{% extends 'posts_base.html' %}

{% block posts_content %}
{% load static %}
{% load vue_widget %}


<!-- Custom Modal for picture posts -->
<div class="modal fade" id="add-picture-post-modal" tabindex="-1" role="dialog" aria-labelledby="picturePostModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="picturePostModalLabel">Post a picture</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="alert alert-warning d-none"><span id="pp-warning"></span></div>
            <form method="POST" id="pp-upload-form" class="align-self-center" action="{% url 'api:media-upload' %}" enctype="multipart/form-data">
              <div class="form-group">
                <label for="pp-title">Title</label>
                <input class="form-control" type="text" id="pp-title" name="title" />
              </div>

              <div class="form-group">
                <label for="pp-file">File</label>
                <input type="file" name="file" class="form-control-file" id="pp-file" accept="image/*">
              </div>

              <div class="form-group">
                <label for="pp-caption">Caption</label>
                <textarea name="text" class="form-control" id="pp-caption">
                            </textarea>
              </div>

              {% csrf_token %}
              <input type="hidden" name="post" value="true">

            </form>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="pp-btn">Post</button>
        </div>
      </div>
    </div>
</div>

{% if user.is_authenticated %}
<script>
  /* Picture post handlers */
  $(document).ready(function(){

        $("#pp-btn").click(function(e){
            e.preventDefault();
            let data = new FormData($("#pp-upload-form")[0]);
            data.append("text", tinyMCE.activeEditor.getContent());

            $.ajax({
                type: "POST",
                url: $("#pp-upload-form").prop("action"),
                enctype: 'multipart/form-data',
                headers: { 'X-CSRFToken': Cookies.get('csrftoken') },
                processData: false,
                contentType: false,
                data: data,
                success: function (data) {
                    $("#pp-warning").text("").parent().toggleClass("d-none");
                    yqnBus.$emit("notify", { title: "Picture posted", body : "Thanks for your contribution" });
                    yqnBus.$emit("data-added");
                    $("#add-picture-post-modal").modal('hide');
                },
                error: function (data) {
                    console.log(data);
                    $("#pp-warning").text(data.responseJSON.error).parent().toggleClass("d-none");
                },
            });
        });
    });

  $("#add-picture-post-modal").on("shown.bs.modal", function(){
    setTimeout(function(){
    console.log("wefewf");
      tinyMCE.init({
          plugins: "autolink code lists emoticons",
          menubar: false,
          toolbar: "undo redo bold italic underline lists emoticons | code",
          statusbar: false,
          selector: "#pp-caption",
      });
    }, 0);
  });
</script>
{% endif %}

<div class="my-3 p-3 bg-light rounded shadow-sm">
    <div class="clearfix border-bottom border-gray pb-2">
      <div class="float-right">

        {% if user.is_authenticated %}
        <div class="btn-group" role="group">
            <button id="add-posts-btn-group-drop" title="Add a post" type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <i class="fas fa-plus-circle"></i>
             Post
          </button>
          <div class="dropdown-menu" aria-labelledby="add-posts-btn-group-drop">
            <a class="dropdown-item" href="#" data-toggle="add-object-modal" data-options='{ "startModel": "Posts", "title": "Add a Post", "success" : "Your post was added thanks for your contribution" }' data-test-id="add-post-btn"><i class="far fa-comment-alt"></i> Message</a>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#add-picture-post-modal"><i class="far fa-image"></i> Picture</a>
          </div>
        </div>

        <button title="Add a Blog, Podcast or News Feed" class="btn btn-secondary btn-sm" data-toggle="add-object-modal" data-options='{ "startModel": "XMLFeeds", "title": "Add a Blog, Podcast or News Feed", "success" :  "Your feed was successfully submitted. Posts will appear the next time it syncs (approx once an hour)" }' data-test-id="add-feed-btn">
            <i class="fas fa-plus-circle"></i>
             Feed
        </button>

        {% else %}
        <a href="{% url "login" %}?next={% url "posts" %}?action=do_post" class="btn btn-primary btn-sm">
            <i class="fas fa-plus-circle"></i>
             Post
        </a>
        <a href="{% url "login" %}?next={% url "posts" %}?action=do_post" class="btn btn-secondary btn-sm">
            <i class="fas fa-plus-circle"></i>
             Feed
        </a>

        {% endif %}

      </div>

      <h6 class="float-left">Posts</h6>
      <a href="#" tabindex=0 class="small float-left ml-2" data-trigger="focus" data-placement="left" data-content="These are posts aggregated from around the web and from
          the YQN community. The views expressed in these posts are their own
          authors and
          not of YQN" data-toggle="popover" data-container="body">
          <i class="far fa-question-circle"></i>
      </a>
    </div>

    <div id="posts-app" v-cloak>
      <posts limit="20" post="{{view.kwargs.pk}}" posts-url="{% url 'posts' %}"></posts>
    </div>

</div>

{% vue_widget "posts.html" %}

  <div id="contact-app">
      <contact></contact>
  </div>
  {% vue_widget "contact.html" %}


{% endblock %}

yqnet/ui_yqn/templates/update_userdetails.html
{% extends "userprofile_base.html" %}

{% block title %}Update Profile{% endblock %}

{% block content %}

{% load bootstrap_tags %}
<script>
    $(document).ready(function(){

        $("#file-upload").change(function(e){
            e.preventDefault();
            let data = new FormData($("#picture-upload-form")[0]);

            $.ajax({
                type: "POST",
                url: $("#picture-upload-form").prop("action"),
                enctype: 'multipart/form-data',
                headers: { 'X-CSRFToken': Cookies.get('csrftoken') },
                processData: false,
                contentType: false,
                data: data,
                success: function (data) {
                    yqnBus.$emit("notify", { title: "Profile picture changed", body : "New profile picture has been uploaded" });
                    $("#avatar").prop("src", data.location);
                    $("#current-avatar").text(data.location);
                },
                error: function (data) {
                    console.log(data);
                },
            });
        });
    });
</script>

<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="clearfix border-bottom border-gray pb-1 mb-0  ">
    <h6>Update your details</h6>
    </div>

    <div class="mt-2 d-flex flex-row">
        <img class="round rounded-circle post-thumb" alt="Avatar" src="{{current_avatar}}" id="avatar" />
        <form method="POST" id="picture-upload-form" class="align-self-center ml-4 mt-2" action="{% url 'api:media-upload' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="file-upload">Profile picture</label>
                <input name="file" class="form-control-file" id="file-upload" placeholder="{{current_avatar}}" accept="image/*" type="file">
                <small>Currently <span id="current-avatar">{{current_avatar}}</span></small>
            </div>
            <input type="hidden" name="avatar" value="true" >
        </form>
    </div>

    <p>Images should be square. e.g. 200px by 200px. Please make sure images are appropriate.</p>

    <div class="mt-2">
        <form method="post">{% csrf_token %} {{ form|as_bootstrap }}
            <input type="submit" class="btn btn-primary d-block ml-auto" value="Update">
        </form>
    </div>

</div>
{% endblock %}

yqnet/ui_yqn/templates/user_page.html
{% load static %}
{% load vue_widget %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{page.title}} (YQN)</title>

    <!-- Font Awesome -->
    <link href="{% static "vendor/fontawesome/css/all.min.css" %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendor/bootstrap/css/offcanvas.css" %}" rel="stylesheet">

    <script src="{% static "vendor/jquery/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "vendor/popper/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/bootstrap-helpers.js" %}"></script>


    {% if DEBUG %}
    <script src="{% static "vendor/vue/vue.js" %}"></script>
    {% else %}
    <script src="{% static "vendor/vue/vue.min.js" %}"></script>
    {% endif %}

    <script src="{% static "vendor/js-cookie/js.cookie.min.js" %}"></script>

    <script src="{% static "js/yqn-utils.js" %}"></script>
    <script>
      yqnUtils.staticUrl = "{% static '' %}";
      yqnUtils.loggedInUser = {
        name: "{{user.username}}",
        id: "{{user.id}}",
      };
    </script>

    <script>
        var pageId = "{{page.id}}";
        var pageTitle = "{{page.title}}";

        $(document).ready(function(){
            $("#contact-btn").click(function(e){
                e.preventDefault();

                let contactData = {
                    modelName: 'GroupPage',
                    objectId: pageId,
                    title: pageTitle,
                };

                yqnBus.$emit("contact", contactData);
            });
        });

    </script>

    {# We only load tinymce when editing as its rather big #}
    {% if editing %}

    <script src="{% static "vendor/tinymce/tinymce.min.js" %}"></script>
    <script>
    var url = "/api/GroupPage/{{page.id}}";
    var uploadUrl = "{% url 'api:media-upload' %}?group_page={{page.id}}";

    $(document).ready(function(){

        tinyMCE.init({
                selector: "textarea",
                plugins: "autolink code lists link emoticons image preview",
                menubar: false,
                toolbar: "undo redo | bold italic underline styleselect | bullist numlist emoticons | alignleft aligncenter alignright | link image | preview code",
                statusbar: false,
                image_list: url + "/images", //Such a stupid bit of UI...
                images_upload_credentials: true,

                file_picker_types: 'image',
                images_upload_url: uploadUrl,
                images_upload_handler: function(blobInfo, success, failure){
                    let data = new FormData();
                    data.append('file', blobInfo.blob(), blobInfo.filename());
                    data.append("group_page", pageId);

                    $.ajax({
                        type: "POST",
                        url: uploadUrl,
                        enctype: 'multipart/form-data',
                        headers: { 'X-CSRFToken': Cookies.get('csrftoken') },
                        processData: false,
                        contentType: false,
                        data: data,
                        success: function(data){
                            success(data.location);
                        },
                        error: function(data){
                            console.log(data);
                            failure(data.responseText);
                        },
                    });
                },

                setup: function(editor){

                },
            });

            $("#delete-page").click(function(e){
                e.preventDefault();
                if (window.confirm("Really delete page?")){
                    yqnUtils.delete(url, function(){
                        window.location = "/";
                    });
                }
            });


            $("#save-page").click(function(e){
                e.preventDefault();

                data = {
                    body: tinyMCE.activeEditor.getContent(),
                    title: $("input[name=title]").val(),
                    slug:  $("input[name=slug]").val(),
                    email:  $("input[name=email]").val(),
                };

                console.log(data);

                $.ajax({
                    type: "PATCH",
                    url: url,
                    data: JSON.stringify(data),
                    contentType: 'application/json',
                    accept: 'application/json',
                    headers: { 'X-CSRFToken': Cookies.get('csrftoken') },
                    success: function () {
                        window.scroll(0,0);
                        yqnBus.$emit("notify", {title: "Saved", body: "All changes have been saved"});
                    },
                    error: function (error) {
                        console.log(error);
                        var errorMsg = '';

                        for (var i in error.responseJSON){
                            errorMsg += i + " - " + error.responseJSON[i];
                        }

                        window.scroll(0,0);
                        yqnBus.$emit("notify", {title: "Error saving", body: errorMsg});
                    },
                });

            });

            $("#open-permissions-modal").click(function(){
               let iframe = $("#permissions-iframe");
               iframe.prop("src", iframe.data("src"));
            });

    });
    </script>
    {% endif %}

  </head>


  <body class="bg-light pt-0">
    {% csrf_token %}

    <div id="notifications-app">
        <notifications></notifications>
    </div>
    {% vue_widget "notifications.html" %}

    <div id="contact-app">
        <contact></contact>
    </div>
    {% vue_widget "contact.html" %}

	  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="mr-auto mr-lg-0" href="{% url "pages" %}">
        <img alt="Young Quaker Network logo"
        src="{% static "imgs/logo_yqn.png" %}"
        data-toggle="tooltip"
        height="15" title="Young Quaker Network" />
      </a>

      <div class="ml-auto">
          <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link p-0" href="{% url 'logout' %}">Logout {% if user.first_name %}
                  {{user.first_name}}
                  {% else %}
                  {{user.username}}
                  {% endif %}
                </a>
              </li>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link p-0" href="{% url "login" %}">Login</a>
              </li>
              {% endif %}

          </ul>
      </div>
    </nav>

        {% if page.eventslocation_set.count > 0 %}
        <nav>
        <div class="nav-scroller bg-white shadow-sm">
            <div class="nav nav-underline">
                <a href="{% url 'user-pages' page.slug %}" class="nav-link">{{page.title}}</a>
                <a href="{% url 'user-page-events' page.slug %}" class="nav-link">Events <i class="fas fa-calendar-alt"></i></a>
            </div>
        </div>
        </nav>
        {% endif %}


	  <main role="main" class="container">

	  <div class="my-3 p-3 bg-white rounded shadow-sm">
		  <div class="clearfix border-bottom border-gray pb-1 mb-0  ">
            {% if editing and user_can_edit %}

            <!-- Temp permissions modal -->
            <div class="modal fade" id="permissions-modal" tabindex="-1" role="dialog" aria-labelledby="permissionsModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="permissionsModalLabel">Permissions</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <iframe id="permissions-iframe" data-src="{% url "user-page-permissions" page.slug page.id %}"
                        style="border: unset; width:100%; min-height: 45vh"
                        ></iframe>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
            <!-- / permissions modal -->

            <div class="d-flex flex-column flex-fill">
                <h3>Editing: <a href="{% url "user-pages" page.slug %}" target="_blank">{{page.title}}</a></h3>
                <div class="form-group">
                    <label for="title-input">Title</label>
                    <input type="text" id="title-input" class="form-control form-control-lg" name="title" value="{{page.title}}" />
                </div>

                <div class="form-group">
                    <label for="slug-input">Slug</label>
                    <input type="text" id="slug-input" class="form-control form-control-lg" name="slug" value="{{page.slug}}" />
                </div>

                <div class="form-group">
                    <label for="email-input">Contact email</label>
                    <input type="email" id="email-input" class="form-control form-control-lg" name="email" value="{{page.email}}" />
                </div>

            </div>

            <p><i class="fas fa-user-edit mr-1"></i><a href="#" id="open-permissions-modal" data-toggle="modal" data-target="#permissions-modal">Edit permissions</a></p>



            {% else %}


              <h3 class="float-left">{{page.title}}</h3>


            {% endif %}


            {% if user_can_edit and not editing %}
              <a href="{% url "user-page-edit" page.slug %}" tabindex=0 class="btn btn-primary btn-sm float-right small" data-test-id="page-edit-btn"><i class="fas fa-edit"></i> Edit</a>
            {% endif %}
          </div>

        {% if editing and user_can_edit %}
            <label for="page-edit-content">Body</label>
            <small>(<a href="https://getbootstrap.com/docs/4.3/layout/overview/" target="_blank">Bootstrap</a> available)</small>
            <textarea id="page-edit-content" style="width:100%; min-height: 800px">{{page.body|safe}}</textarea>
            <div class="d-flex flex-row mt-2 mb-2">

                <button class="btn btn-danger small mr-auto" id="delete-page">Delete</button>
                <a href="{% url "user-pages" page.slug %}" class="btn btn-secondary small mr-2">Cancel</a>
                <button class="btn btn-primary small" id="save-page">Save</button>
            </div>
        {% else %}

          <div class="container">
             {{page.body|safe}}
          </div>

        {% if page.has_email %}
        <button class="ml-auto d-block btn btn-sm btn-secondary mt-2" id="contact-btn"><i class="fas fa-envelope"></i> Contact</button>
        {% endif %}

        {% endif %}

		  <small class="d-block text-right mt-3">
			  {{page.last_modified}}
          </small>
	  </div>

	  </main>
  </body>
</html>